#!/bin/bash 

##  This example script can be used on the computer with the sound device.
##  It starts up a loop that starts 'netplay' repeatedly.
##  Adjust the values of the various variables before starting it.

##  See the script 'send_to_listenloop' for an example how to send audio
##  date from another machine.

# to avoid accidentally sent data on local network
NEEDMAGIC=weasdDSwfw8773naSEgeoQ

# sound device
ALSADEVICE="hw:0,0"
SAMPLEFORMAT=S32_LE
ALSABUFSIZE=8192  # enlarge if playback is unstable
# slight adjustment in case of over- or underrun
EXTRABYTESPERSEC=0

# how to call the 'netplay' program  
#NETPLAY=netplay
export LD_LIBRARY_PATH=/root/alsa/lib/:
NETPLAY=netplay_ALSANC # we use version with patched alsa lib

# some more netplay options
INBUFSIZE=20000
INCHUNKSIZE=0   # use minimal possible amount
FREQ=1000    # 1000 or 2000 are good values for USB interfaces
NONBLOCK=--non-blocking-write
# uncomment until fine tuning is done:
#VERBOSE=--verbose

# we give 'netplay' highest priority in the real time scheduler
# (start with sudo or make 'chrt' setuid root)
CHRT="chrt -f 99"


while true; do
  # reset/unset variables
  unset MAGIC
  unset FROMHOST
  unset FROMPORT
  unset SAMPLERATE

  # listen on port 5501 for variables 
  params=`nc -l -p 5501` 
  eval $params
  unset params

  if [ X$MAGIC == X$NEEDMAGIC ]; then
      # leave the other side time to start up sender 
      sleep 0.2

      # and now start the player program
      $CHRT $NETPLAY $VERBOSE --host=$FROMHOST --port=$FROMPORT --buffer-size=$INBUFSIZE --input-size=$INCHUNKSIZE --loops-per-second=$FREQ --sample-rate=$SAMPLERATE --sample-format=$SAMPLEFORMAT --hw-buffer=$ALSABUFSIZE --device=$ALSADEVICE --extra-bytes-per-second=$EXTRABYTESPERSEC $NONBLOCK
  fi
  # do nothing if MAGIC was not sent or not correct
done 


