#!/bin/bash

##  Example script to play a sound file by sending it to another host which
##  runs 'netplay' (see example script 'listenloop').
##  Start this with the sound file as argument:
##       send_to_listenloop mymusic.flac
##
##  In this example we use 'sox' to decode the file and resample to
##  96000/32 format and send the data with 'bufnet' (i.e.,
##  4 x 2 x 96000 = 768000 bytes per second) to the remote machine.
##  
##  (on my machines I found an underrun of 'netplay' after a few minutes
##  and adjust it by using 'bufnet' with option '--extra-bytes-per-second=20')
##  
##  (Actually, I'm using a more sophisticated script which also pipes the
##  audio stream through 'volrace' and 'brutefir' for localization and room
##  correction.)
##

# name or ip of host running this script
THISHOST=myhost
# name or ip of host running 'netplay'
PLAYER=playhost
PORT=6110

# tell playhost to start 'netplay'
echo 'MAGIC=weasdDSwfw8773naSEgeoQ;FROMHOST='$THISHOST';FROMPORT='$PORT';SAMPLERATE=96000' | nc -q 0 $PLAYER 5501


sox $1 -t raw -e signed -b 32 - vol 0.6  rate -v -I 96000 | \
     chrt -r 99 bufnet --buffer-size=8096 --input-size=0  \
     --bytes-per-second=768000 --loops-per-second=2000 --port=6110 \
     --extra-bytes-per-second=0 

