#!/bin/bash

##  Example script to play a sound file by sending it to another host which
##  runs 'playhrt' (see example script 'listenloop').
##  Start this with the sound file as argument:
##       send_to_listenloop mymusic.flac
##
##  In this example we use 'sox' to decode the file and resample to
##  96000/32 format and send the data with 'bufhrt' (i.e.,
##  4 x 2 x 96000 = 768000 bytes per second) to the remote machine.
##  
##  (on my machines I found an underrun of 'playhrt' after a few minutes
##  and adjusted this by using 'bufhrt' with option 
##  '--extra-bytes-per-second=20')
##  
##  (Actually, I'm using a more sophisticated script which also pipes the
##  audio stream through 'volrace' and 'brutefir' for localization and room
##  correction.)
##

# name or ip of host running this script
THISHOST=`hostname`
# name or ip of host running 'playhrt'
PLAYER=playhost
PORT=6110

# tell playhost to start 'playhrt'
echo 'MAGIC=weasdDSwfw8773naSEgeoQ;FROMHOST='$THISHOST';FROMPORT='$PORT';SAMPLERATE=96000' | nc -q 0 $PLAYER 5501


sox $1 -t raw -e signed -b 32 - vol 0.6  rate -v -I 96000 | \
     chrt -r 99 bufhrt --buffer-size=8096 --input-size=0  \
     --bytes-per-second=768000 --loops-per-second=2000 --port=6110 \
     --extra-bytes-per-second=0 
# and here is a variant with 'volrace'
#sox $1 -t raw -e floating-point -b 64 - | \
#     sox  -t raw -c2 -r 44100 -e floating-point -b 64 - \
#          -t raw -e floating-point -b 64 - vol 0.8  rate -v -I 96000 | \
#     volrace --race-delay=28 --race-volume=0.22 | \
#     sox -t raw -c2 -r 96000 -e floating-point -b 64 - \
#         -t raw -e signed -b 32 - \
#     chrt -r 99 bufhrt --buffer-size=8096 --input-size=0  \
#          --bytes-per-second=768000 --loops-per-second=2000 --port=6110 \
#          --extra-bytes-per-second=0 


